spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  session:
    timeout: 86400 # 세션 기간 : 24시간

  datasource:
    url: jdbc:h2:mem:booklog
    username: sanghee
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

jwt:
  jwt-key: ${secret-key}

server:
  servlet:
    session:
      cookie:
        max-age: 172800 # 쿠키 기간 : 48시간