### 북마크 리스트 출력
GET http://localhost:8080/users/bookmarks?page=1&size=4



### 북마크 추가
POST http://localhost:8080/users/bookmarks/1
Content-Type: application/json


### 북마크 삭제
DELETE http://localhost:8080/users/bookmarks/1

### 북마크 상태 체크
GET http://localhost:8080/users/bookmarks/2

### 북마크 토글
POST http://localhost:8080/bookmarks/2
