/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BookCard: typeof import('./src/components/BookCard.vue')['default']
    BookmarkButton: typeof import('./src/components/BookmarkButton.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    Comments: typeof import('./src/components/Comments.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FeaturesWidget: typeof import('./src/components/landing/FeaturesWidget.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FooterWidget: typeof import('./src/components/landing/FooterWidget.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeroWidget: typeof import('./src/components/landing/HeroWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/landing/HighlightsWidget.vue')['default']
    LikeButton: typeof import('./src/components/LikeButton.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MyMenu: typeof import('./src/components/MyMenu.vue')['default']
    PostView: typeof import('./src/components/PostView.vue')['default']
    PricingWidget: typeof import('./src/components/landing/PricingWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    TopbarWidget: typeof import('./src/components/landing/TopbarWidget.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
